### ISSUE TITLE
Matchmaking Server Design?

### ISSUE THREAD

**Issue by lemt93** [lemt93/pingpong-server#3]
Responsibility:
- Handling client connections
- Redirecting connections to game worlds/game servers
- Also responsible for creating new game worlds/states, even spawn a new game servers if needed.

**Comment by lemt93** [comment]
A matchmaker receives matchmaking request from players/clients and processes them.
- Grouping players based on some set of defined rules, such ash: friends play together, region...

For this purpose, I think it's best to use a Queue data storage/structure and event loop to process them.
- Queue storage (mem-store) -> Redis

Whenever a client choose to go in matchmaking, the websocket connection is not yet necessary.
Client sends a request, we put them in a queue.
And then whenever a match found, we notify client by using Server-Sent Event.
After that a connection should be made to the **Game Server?**
Thoughts on this? @dungtang93

**Comment by dungtang93** [comment]
> For this purpose, I think it's best to use a Queue data storage/structure and event loop to process them.   

Yes, LGTM

> Whenever a client choose to go in matchmaking, the websocket connection is not yet necessary.

Why not? we can just create the WS connection right there and skip all the HTTP part ([SSE is pretty bad in browser support](https://caniuse.com/#feat=eventsource) and requires more overhead)

**Comment by lemt93** [comment]
> Queue storage (mem-store) -> Redis
Just found out KeyDB is an alternative for Redis with even higher performance.

> Why not? we can just create the WS connection right there and skip all the HTTP part (SSE is pretty bad in browser support and requires more overhead)
Matchmaking / queueing / lobby could take forever to resolve... An open WS connection itself, in this case, becomes the overhead / unecessary.
